name: CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet: [ "9.0.x" ]

    steps:
      - name: Download Artifact
        if: success()
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          name: wol-server

      - name: Run unit and integration tests
        run: dotnet test --no-build -c Release --verbosity normal
